AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  samaggi-games-admin

  Sample SAM Template for samaggi-games-admin

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"


Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            Auth:
              ApiKeyRequired: true

  TeamExistsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.team_exists
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        TeamExists:
          Type: Api
          Properties:
            Path: /team-exists
            Method: get
            Auth:
              ApiKeyRequired: true
              DefaultAuthorizer: SSGamesAPIAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"


  AddPlayer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.add_player
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        AddPlayer:
          Type: Api
          Properties:
            Path: /add-player
            Method: get
            Auth:
              ApiKeyRequired: true
              DefaultAuthorizer: SSGamesAPIAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"

  DeletePlayer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.delete_player
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        DeletePlayer:
          Type: Api
          Properties:
            Path: /delete-player
            Method: get
            Auth:
              ApiKeyRequired: true
              DefaultAuthorizer: SSGamesAPIAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"

  GetTable:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.get_table
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        GetTable:
          Type: Api
          Properties:
            Path: /get-table
            Method: get
            Auth:
              DefaultAuthorizer: SSGamesAPIAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"

  GetPlayerID:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.get_player_id
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        GetPlayerID:
          Type: Api
          Properties:
            Path: /get-player-id
            Method: get
            Auth:
              ApiKeyRequired: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"

  SSGamesAPIUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: SSGamesAPIUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  SSGamesAPIUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref SSGamesAPIUserPool
      ClientName: SSGamesAPI
      GenerateSecret: false

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  AddPlayerGateway:
    Description: "API Gateway for AddPlayer"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add-player/"
  AddPlayerFunction:
    Description: "ARN for AddPlayer"
    Value: !GetAtt AddPlayer.Arn
  AddPlayerIam:
    Description: "The IAM Role for AddPlayer"
    Value: !GetAtt AddPlayer.Arn
  DeletePlayerGateway:
    Description: "API Gateway for DeletePlayer"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete-player/"
  DeletePlayerFunction:
    Description: "ARN for DeletePlayer"
    Value: !GetAtt DeletePlayer.Arn
  DeletePlayerIam:
    Description: "The IAM Role for DeletePlayer"
    Value: !GetAtt DeletePlayer.Arn
  GetTableGateway:
    Description: "API Gateway for GetTable"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-table/"
  GetTableFunction:
    Description: "ARN for GetTable"
    Value: !GetAtt GetTable.Arn
  GetTableIam:
    Description: "The IAM Role for GetTable"
    Value: !GetAtt GetTable.Arn
  GetPlayerIDGateway:
    Description: "API Gateway for GetPlayerID"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-player-id/"
  GetPlayerIDFunction:
    Description: "ARN for GetPlayerID"
    Value: !GetAtt GetPlayerID.Arn
  GetPlayerIDIam:
    Description: "The IAM Role for GetPlayerID"
    Value: !GetAtt GetPlayerID.Arn

